### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by RummanUK** [tanjinbd/LiberationWar5#2]
The first intent where the country map is showed with overlapping of pins and sections. it appears that area is fixed and square, I think it should be as per background map area. Let me know your opinion

**Comment by tanjinbd** [comment]
Yes, agreed thats known issue, actually I am working on creating the layer from Google/Open Maps geo location and co-ordinates. (the pin point coordinates are taken from an in built SQL light table). Will update that on next version

**Comment by RummanUK** [comment]
Great, will be eagerly waiting for the updates.
